var homeSiteConfig =
    {
        "baseURL": "http://help.ptc.com/creo_hc/creo30_pma_hc/french",
        "siteLanguage": "fr",
        "availableLanguages": ["en", "de", "es", "fr", "it", "ru", "ja", "ko", "zh_CN", "zh_TW"],
        "availableLanguagesSelector": {
            selectorID: "siteLanguageSelectorID",
            selectorName : "siteLanguageSelector",
            selectorStyle : "",
            "availableLanguagesSites": {
                "en": {
                    "displayItem": "English",
                    "siteURL": "http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/"
                },
                "de": {
                    "displayItem": "Deutsch",
                    "siteURL": "http://help.ptc.com/creo_hc/creo30_pma_hc/german/"
                },
                "es": {
                    "displayItem": "Español",
                    "siteURL": "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/"
                },
                "fr": {
                    "displayItem": "Français",
                    "siteURL": "http://help.ptc.com/creo_hc/creo30_pma_hc/french/"
                },
                "it": {
                    "displayItem": "Italiano",
                    "siteURL": "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/"
                },
                "ru": {
                    "displayItem": "Pусский",
                    "siteURL": "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/"
                },
                "ja": {
                    "displayItem": "日本語",
                    "siteURL": "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/"
                },
                "ko": {
                    "displayItem": "한국어",
                    "siteURL": "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/"
                },
                "zh_CN": {
                    "displayItem": "简体中文",
                    "siteURL": "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/"
                },
                "zh_TW": {
                    "displayItem": "繁體中文",
                    "siteURL": "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/"
                }
            }
        },
		
		// Translate the text between square brackets in this order ["en", "de", "es", "fr", "it", "ru", "ja", "ko", "zh_CN", "zh_TW"]

        searchComponentProperties: {
            searchButtonValue: ["Search", "Suchen", "Buscar", "Rechercher", "Cerca", "поиск", "サーチ", "검색", "搜索", "搜索"],
            defaultSearchBoxText: [
                                    "Search Documents, Videos, Communities, and more",
                                    "Suchen Sie nach Dokumenten, Videos, Communities, etc.",
                                    "Búsqueda de documentos, vídeos, comunidades, etc.",
                                    "Rechercher des documents, des vidéos, des communautés, etc.",
                                    "Ricerca di documenti, video, community, ecc.",
                                    "Поиск документов, видео, сообществ и т.д.",
                                    "マニュアル、ビデオ、コミュニティなどをサーチ",
                                    "문서, 비디오, 커뮤니티 등 검색",
                                    "搜索文档、视频、社区和更多",
                                    "搜尋文件、視訊及社群等等。"
                                   ],
            searchBoxUnfocusedColor: "#C9C9C7",
            searchButtonID: "gcseSearchComponentButton"
        },

		// Translate the text between square brackets in this order ["en", "de", "es", "fr", "it", "ru", "ja", "ko", "zh_CN", "zh_TW"]
		
        siteSourcesProperties: {
            defaultNoSelectionSource: 1,
            defaultNoSelectionSourceText : ["Other resources", "Andere Ressourcen", "Otros recursos", "Autres ressources", "Altre risorse",
                                            "Другие ресурсы", "その他のリソース", "기타 리소스", "其他资源", "其他資源"]
        },

        siteSources:
            {
                // Translate the text between square brackets in this order ["en", "de", "es", "fr", "it", "ru", "ja", "ko", "zh_CN", "zh_TW"]
                "All": {
                    "displayItem" : ["All Sites", "Alle Sites","Todos los sitios","Tous les sites","Tutti i siti","Все сайты","すべてのサイト","모든 사이트","所有站点","全部網站"],
                },
                "Learning Exchange": {
                    "displayItem" : ["PTC Learning Exchange", "PTC Learning Exchange","PTC Learning Exchange","PTC Learning Exchange","PTC Learning Exchange","PTC Learning Exchange","PTC Learning Exchange","PTC Learning Exchange","PTC Learning Exchange","PTC Learning Exchange"],
                    "siteURL": ["http://learningexchange.ptc.com", "http://learningexchange.ptc.com", "http://learningexchange.ptc.com", "http://learningexchange.ptc.com", "http://learningexchange.ptc.com", "http://learningexchange.ptc.com", "http://learningexchange.ptc.com", "http://learningexchange.ptc.com", "http://learningexchange.ptc.com", "http://learningexchange.ptc.com"]
                },
                "User Community": {
                    "displayItem" : ["PTC User Community", "PTC Benutzer-Community","Comunidad de usuarios de PTC","Communauté des utilisateurs PTC","Community di utenti PTC","Сообщество пользователей PTC","PTC ユーザーコミュニティ","PTC 사용자 커뮤니티","PTC 用户社区","PTC 使用者社群"],
					"siteURL": ["http://communities.ptc.com/community/creo", "http://communities.ptc.com/community/creo", "http://communities.ptc.com/community/creo", "http://communities.ptc.com/community/creo", "http://communities.ptc.com/community/creo", "http://communities.ptc.com/community/creo", "http://communities.ptc.com/community/creo", "http://communities.ptc.com/community/creo", "http://communities.ptc.com/community/creo", "http://communities.ptc.com/community/creo"]
                },
                "YouTube": {
                    "displayItem" : ["PTC YouTube channel", "PTC auf YouTube","Canal de YouTube de PTC","PTC YouTube","Canale YouTube PTC","Канал PTC YouTube","PTC YouTube チャンネル","PTC YouTube 채널","PTC YouTube 频道","PTC YouTube 頻道"],
                    "siteURL": ["http://www.youtube.com/user/ptcstudio", "http://www.youtube.com/user/ptcstudio", "http://www.youtube.com/user/ptcstudio", "http://www.youtube.com/user/ptcstudio", "http://www.youtube.com/user/ptcstudio", "http://www.youtube.com/user/ptcstudio", "http://www.youtube.com/user/ptcstudio", "http://www.youtube.com/user/ptcstudio", "http://www.youtube.com/user/ptcstudio", "http://www.youtube.com/user/ptcstudio"]

                }
            },

        // Left side list of module links which is also used for the drop down list filter.
        siteModulesProperties: {
            divClassID: "creo_modules_container",
            divStyle: "width: 270px; float: left; visibility: visible; height: 430px; margin-top: 10px;",
            listHeadingClassID: "siteModulesHeaderID",
            // listHeadingText : Translate the text between square brackets in this order ["en", "de", "es", "fr", "it", "ru", "ja", "ko", "zh_CN", "zh_TW"]
                    listHeadingText : ["Help Modules", "Hilfe-Module","Módulos de la ayuda","Modules d&apos;aide","Moduli della Guida","Модули справки","ヘルプモジュール","도움말 모듈","帮助模块","說明模組"],
            listItemID: "siteModuleLinkID",
            isModuleList: true
        },

        // displayItem : Translate the text between square brackets in this order ["en", "de", "es", "fr", "it", "ru", "ja", "ko", "zh_CN", "zh_TW"]
        "siteModules": {
            "All": {
                "baseURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/"],
                    "displayItem" : ["All Help Modules", "Alle Hilfe-Module","Todos los módulos de la ayuda","Tous les modules d&apos;aide","Tutti i moduli della Guida","Все модули справки","すべてのヘルプモジュール","모든 도움말 모듈","所有帮助模块","全部說明模組"],
            },
			
			"Using the Help": {
                "baseURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/pma/introduction/", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/pma/introduction/", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/pma/introduction/", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/pma/introduction/", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/pma/introduction/", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/pma/introduction/", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/pma/introduction/", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/pma/introduction/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/pma/introduction/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/pma/introduction/"],
                "moduleURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/index.html#page/pma/introduction/about_PTC_creo_help.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/index.html#page/pma/introduction/about_PTC_creo_help.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/index.html#page/pma/introduction/about_PTC_creo_help.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/index.html#page/pma/introduction/about_PTC_creo_help.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/index.html#page/pma/introduction/about_PTC_creo_help.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/index.html#page/pma/introduction/about_PTC_creo_help.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/index.html#page/pma/introduction/about_PTC_creo_help.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/index.html#page/pma/introduction/about_PTC_creo_help.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/index.html#page/pma/introduction/about_PTC_creo_help.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/index.html#page/pma/introduction/about_PTC_creo_help.html"],
                    "displayItem" : ["Using the Help", "Hilfe verwenden","Uso del Centro de ayuda","Utilisation de l&apos;aide","Utilizzo della Guida","Использование справки","ヘルプの使用","도움말 사용","使用帮助","使用「說明中心」"],
            },				
			
			"What's New: PTC Creo Parametric 3.0": {
                "baseURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/pma/whats_new_pma/", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/pma/whats_new_pma/", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/pma/whats_new_pma/", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/pma/whats_new_pma/", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/pma/whats_new_pma/", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/pma/whats_new_pma/", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/pma/whats_new_pma/", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/pma/whats_new_pma/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/pma/whats_new_pma/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/pma/whats_new_pma/"],
                "moduleURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/pma/whats_new_pma/Fundamentals_ImprovementsInMassProperties-65F02A86_2_3.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/pma/whats_new_pma/Fundamentals_ImprovementsInMassProperties-65F02A86_2_3.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/pma/whats_new_pma/Fundamentals_ImprovementsInMassProperties-65F02A86_2_3.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/pma/whats_new_pma/Fundamentals_ImprovementsInMassProperties-65F02A86_2_3.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/pma/whats_new_pma/Fundamentals_ImprovementsInMassProperties-65F02A86_2_3.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/pma/whats_new_pma/Fundamentals_ImprovementsInMassProperties-65F02A86_2_3.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/pma/whats_new_pma/Fundamentals_ImprovementsInMassProperties-65F02A86_2_3.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/pma/whats_new_pma/Fundamentals_ImprovementsInMassProperties-65F02A86_2_3.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/pma/whats_new_pma/Fundamentals_ImprovementsInMassProperties-65F02A86_2_3.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/pma/whats_new_pma/Fundamentals_ImprovementsInMassProperties-65F02A86_2_3.html"],
                    "displayItem" : ["What's New: PTC Creo Parametric 3.0", "Neue Funktionen: PTC Creo Parametric 3.0","Novedades de PTC Creo Parametric 3.0","Nouveautés : PTC Creo Parametric 3.0","Novità di PTC Creo Parametric 3.0","Новые функции и возможности: PTC Creo Parametric 3.0","最新情報: PTC Creo Parametric 3.0","새로운 기능: PTC Creo Parametric 3.0","新增功能：PTC Creo Parametric 3.0","新功能：PTC Creo Parametric 3.0"],

            },
            "PTC Creo Parametric Tutorials": {
                "baseURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/pma/tutorials_pma/", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/pma/tutorials_pma/", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/pma/tutorials_pma/", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/pma/tutorials_pma/", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/pma/tutorials_pma/", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/pma/tutorials_pma/", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/pma/tutorials_pma/", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/pma/tutorials_pma/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/pma/tutorials_pma/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/pma/tutorials_pma/"],
                "moduleURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/index.html#page/pma/tutorials_pma/creo_parametric/aux_files/pma_tutorials.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/index.html#page/pma/tutorials_pma/creo_parametric/aux_files/pma_tutorials.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/index.html#page/pma/tutorials_pma/creo_parametric/aux_files/pma_tutorials.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/index.html#page/pma/tutorials_pma/creo_parametric/aux_files/pma_tutorials.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/index.html#page/pma/tutorials_pma/creo_parametric/aux_files/pma_tutorials.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/index.html#page/pma/tutorials_pma/creo_parametric/aux_files/pma_tutorials.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/index.html#page/pma/tutorials_pma/creo_parametric/aux_files/pma_tutorials.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/index.html#page/pma/tutorials_pma/creo_parametric/aux_files/pma_tutorials.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/index.html#page/pma/tutorials_pma/creo_parametric/aux_files/pma_tutorials.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/index.html#page/pma/tutorials_pma/creo_parametric/aux_files/pma_tutorials.html"],
                    "displayItem" : ["PTC Creo Parametric Tutorials", "PTC Creo Parametric Lernprogramme","Cursos de PTC Creo Parametric","Didacticiels PTC Creo Parametric","Esercitazioni di PTC Creo Parametric","Учебники по PTC Creo Parametric","PTC Creo Parametric チュートリアル","PTC Creo Parametric 자습서","PTC Creo Parametric 教程","PTC Creo Parametric 教學專區"],

            },
            "Fundamentals": {
                "baseURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/pma/fundamentals/", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/pma/fundamentals/", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/pma/fundamentals/", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/pma/fundamentals/", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/pma/fundamentals/", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/pma/fundamentals/", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/pma/fundamentals/", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/pma/fundamentals/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/pma/fundamentals/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/pma/fundamentals/"],
                "moduleURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/index.html#page/pma/fundamentals/creo_parametric/aux_files/basicproe.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/index.html#page/pma/fundamentals/creo_parametric/aux_files/basicproe.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/index.html#page/pma/fundamentals/creo_parametric/aux_files/basicproe.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/index.html#page/pma/fundamentals/creo_parametric/aux_files/basicproe.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/index.html#page/pma/fundamentals/creo_parametric/aux_files/basicproe.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/index.html#page/pma/fundamentals/creo_parametric/aux_files/basicproe.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/index.html#page/pma/fundamentals/creo_parametric/aux_files/basicproe.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/index.html#page/pma/fundamentals/creo_parametric/aux_files/basicproe.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/index.html#page/pma/fundamentals/creo_parametric/aux_files/basicproe.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/index.html#page/pma/fundamentals/creo_parametric/aux_files/basicproe.html"],
                    "displayItem" : ["Fundamentals ", "Grundlagen ","Principios fundamentales ","Principes de base ","Nozioni fondamentali ","Основы ","基本的な機能 ","기초 ","基础功能 ","基礎原理 "],

            },
            "Data Management": {
                "baseURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/pma/data_management/", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/pma/data_management/", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/pma/data_management/", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/pma/data_management/", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/pma/data_management/", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/pma/data_management/", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/pma/data_management/", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/pma/data_management/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/pma/data_management/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/pma/data_management/"],
                "moduleURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/index.html#page/pma/data_management/creo_parametric/aux_files/datamanagement.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/index.html#page/pma/data_management/creo_parametric/aux_files/datamanagement.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/index.html#page/pma/data_management/creo_parametric/aux_files/datamanagement.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/index.html#page/pma/data_management/creo_parametric/aux_files/datamanagement.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/index.html#page/pma/data_management/creo_parametric/aux_files/datamanagement.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/index.html#page/pma/data_management/creo_parametric/aux_files/datamanagement.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/index.html#page/pma/data_management/creo_parametric/aux_files/datamanagement.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/index.html#page/pma/data_management/creo_parametric/aux_files/datamanagement.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/index.html#page/pma/data_management/creo_parametric/aux_files/datamanagement.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/index.html#page/pma/data_management/creo_parametric/aux_files/datamanagement.html"],
                    "displayItem" : ["Data Management", "Datenverwaltung","Gestión de datos","Gestion des données","Gestione dei dati","Управление данными","データ管理","데이터 관리","数据管理","資料管理"],

            },
            "Design Exploration": {
                "baseURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/pma/design_exploration/", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/pma/design_exploration/", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/pma/design_exploration/", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/pma/design_exploration/", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/pma/design_exploration/", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/pma/design_exploration/", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/pma/design_exploration/", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/pma/design_exploration/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/pma/design_exploration/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/pma/design_exploration/"],
                "moduleURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/index.html#page/pma/design_exploration/creo_parametric/aux_files/design_exploration.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/index.html#page/pma/design_exploration/creo_parametric/aux_files/design_exploration.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/index.html#page/pma/design_exploration/creo_parametric/aux_files/design_exploration.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/index.html#page/pma/design_exploration/creo_parametric/aux_files/design_exploration.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/index.html#page/pma/design_exploration/creo_parametric/aux_files/design_exploration.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/index.html#page/pma/design_exploration/creo_parametric/aux_files/design_exploration.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/index.html#page/pma/design_exploration/creo_parametric/aux_files/design_exploration.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/index.html#page/pma/design_exploration/creo_parametric/aux_files/design_exploration.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/index.html#page/pma/design_exploration/creo_parametric/aux_files/design_exploration.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/index.html#page/pma/design_exploration/creo_parametric/aux_files/design_exploration.html"],
                    "displayItem" : ["Design Exploration", "Design Exploration","Exploración de diseño","Exploration de la conception","Esplorazione progetto","Исследование конструкции","設計の探索","설계 탐색","设计探索","設計瀏覽"],

            },
            "Part Modeling": {
                "baseURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/pma/part_modeling/", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/pma/part_modeling/", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/pma/part_modeling/", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/pma/part_modeling/", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/pma/part_modeling/", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/pma/part_modeling/", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/pma/part_modeling/", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/pma/part_modeling/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/pma/part_modeling/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/pma/part_modeling/"],
                "moduleURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/index.html#page/pma/part_modeling/creo_parametric/aux_files/partmodeling.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/index.html#page/pma/part_modeling/creo_parametric/aux_files/partmodeling.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/index.html#page/pma/part_modeling/creo_parametric/aux_files/partmodeling.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/index.html#page/pma/part_modeling/creo_parametric/aux_files/partmodeling.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/index.html#page/pma/part_modeling/creo_parametric/aux_files/partmodeling.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/index.html#page/pma/part_modeling/creo_parametric/aux_files/partmodeling.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/index.html#page/pma/part_modeling/creo_parametric/aux_files/partmodeling.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/index.html#page/pma/part_modeling/creo_parametric/aux_files/partmodeling.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/index.html#page/pma/part_modeling/creo_parametric/aux_files/partmodeling.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/index.html#page/pma/part_modeling/creo_parametric/aux_files/partmodeling.html"],
                    "displayItem" : ["Part Modeling", "Modellierung von Bauteilen","Modelado de piezas","Modélisation de pièces","Modellazione delle parti","Моделирование деталей","部品モデリング","부품 모델링","零件建模","零件建模"],
            },
            "Data Exchange": {
                "baseURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/pma/data_exchange/", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/pma/data_exchange/", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/pma/data_exchange/", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/pma/data_exchange/", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/pma/data_exchange/", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/pma/data_exchange/", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/pma/data_exchange/", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/pma/data_exchange/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/pma/data_exchange/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/pma/data_exchange/"],
                "moduleURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/index.html#page/pma/data_exchange/creo_parametric/aux_files/dataexchange.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/index.html#page/pma/data_exchange/creo_parametric/aux_files/dataexchange.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/index.html#page/pma/data_exchange/creo_parametric/aux_files/dataexchange.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/index.html#page/pma/data_exchange/creo_parametric/aux_files/dataexchange.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/index.html#page/pma/data_exchange/creo_parametric/aux_files/dataexchange.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/index.html#page/pma/data_exchange/creo_parametric/aux_files/dataexchange.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/index.html#page/pma/data_exchange/creo_parametric/aux_files/dataexchange.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/index.html#page/pma/data_exchange/creo_parametric/aux_files/dataexchange.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/index.html#page/pma/data_exchange/creo_parametric/aux_files/dataexchange.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/index.html#page/pma/data_exchange/creo_parametric/aux_files/dataexchange.html"],
                    "displayItem" : ["Data Exchange", "Datenaustausch","Intercambio de datos","Echange de données","Scambio dati","Обмен данными","データ交換","데이터 교환","数据交换","資料交換"],
            },
            "Detailed Drawings": {
                "baseURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/pma/detail/", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/pma/detail/", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/pma/detail/", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/pma/detail/", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/pma/detail/", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/pma/detail/", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/pma/detail/", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/pma/detail/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/pma/detail/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/pma/detail/"],
                "moduleURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/index.html#page/pma/detail/creo_parametric/aux_files/detailing.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/index.html#page/pma/detail/creo_parametric/aux_files/detailing.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/index.html#page/pma/detail/creo_parametric/aux_files/detailing.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/index.html#page/pma/detail/creo_parametric/aux_files/detailing.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/index.html#page/pma/detail/creo_parametric/aux_files/detailing.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/index.html#page/pma/detail/creo_parametric/aux_files/detailing.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/index.html#page/pma/detail/creo_parametric/aux_files/detailing.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/index.html#page/pma/detail/creo_parametric/aux_files/detailing.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/index.html#page/pma/detail/creo_parametric/aux_files/detailing.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/index.html#page/pma/detail/creo_parametric/aux_files/detailing.html"],
                    "displayItem" : ["Detailed Drawing", "Zeichnungserstellung","Diseño detallado","Dessins détaillés","Disegno dettagliato","Детализированные чертежи","詳細図面","세부 드로잉","详细绘图","細節工程圖"],
            },
            "Layout": {
                "baseURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/pma/layout/", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/pma/layout/", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/pma/layout/", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/pma/layout/", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/pma/layout/", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/pma/layout/", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/pma/layout/", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/pma/layout/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/pma/layout/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/pma/layout/"],
                "moduleURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/index.html#page/pma/layout/creo_parametric/aux_files/layout.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/index.html#page/pma/layout/creo_parametric/aux_files/layout.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/index.html#page/pma/layout/creo_parametric/aux_files/layout.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/index.html#page/pma/layout/creo_parametric/aux_files/layout.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/index.html#page/pma/layout/creo_parametric/aux_files/layout.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/index.html#page/pma/layout/creo_parametric/aux_files/layout.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/index.html#page/pma/layout/creo_parametric/aux_files/layout.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/index.html#page/pma/layout/creo_parametric/aux_files/layout.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/index.html#page/pma/layout/creo_parametric/aux_files/layout.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/index.html#page/pma/layout/creo_parametric/aux_files/layout.html"],
                    "displayItem" : ["Layout", "Layout","Esquema (Layout)","Schéma","Layout","Компоновка","レイアウト","레이아웃","布局","配置圖"],
            },
            "Surfacing": {
                "baseURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/pma/surfacing/", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/pma/surfacing/", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/pma/surfacing/", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/pma/surfacing/", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/pma/surfacing/", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/pma/surfacing/", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/pma/surfacing/", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/pma/surfacing/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/pma/surfacing/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/pma/surfacing/"],
                "moduleURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/index.html#page/pma/surfacing/creo_parametric/aux_files/surfacing.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/index.html#page/pma/surfacing/creo_parametric/aux_files/surfacing.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/index.html#page/pma/surfacing/creo_parametric/aux_files/surfacing.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/index.html#page/pma/surfacing/creo_parametric/aux_files/surfacing.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/index.html#page/pma/surfacing/creo_parametric/aux_files/surfacing.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/index.html#page/pma/surfacing/creo_parametric/aux_files/surfacing.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/index.html#page/pma/surfacing/creo_parametric/aux_files/surfacing.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/index.html#page/pma/surfacing/creo_parametric/aux_files/surfacing.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/index.html#page/pma/surfacing/creo_parametric/aux_files/surfacing.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/index.html#page/pma/surfacing/creo_parametric/aux_files/surfacing.html"],
                    "displayItem" : ["Surfacing", "Flächenkonstruktion","Diseño de superficies","Surfaçage","Creazione di superfici","Поверхностное моделирование","サーフェス作成","서피싱","曲面设计","曲面建模"],
            },
            "Rendering": {
                "baseURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/pma/rendering/", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/pma/rendering/", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/pma/rendering/", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/pma/rendering/", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/pma/rendering/", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/pma/rendering/", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/pma/rendering/", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/pma/rendering/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/pma/rendering/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/pma/rendering/"],
                "moduleURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/index.html#page/pma/rendering/creo_parametric/aux_files/rendering.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/index.html#page/pma/rendering/creo_parametric/aux_files/rendering.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/index.html#page/pma/rendering/creo_parametric/aux_files/rendering.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/index.html#page/pma/rendering/creo_parametric/aux_files/rendering.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/index.html#page/pma/rendering/creo_parametric/aux_files/rendering.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/index.html#page/pma/rendering/creo_parametric/aux_files/rendering.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/index.html#page/pma/rendering/creo_parametric/aux_files/rendering.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/index.html#page/pma/rendering/creo_parametric/aux_files/rendering.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/index.html#page/pma/rendering/creo_parametric/aux_files/rendering.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/index.html#page/pma/rendering/creo_parametric/aux_files/rendering.html"],
                    "displayItem" : ["Rendering", "Rendering","Fotorrealismo","Rendu","Rendering","Рендеринг","レンダリング","렌더링","渲染","彩現"],
            },
            "Assembly Design": {
                "baseURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/pma/assembly/", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/pma/assembly/", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/pma/assembly/", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/pma/assembly/", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/pma/assembly/", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/pma/assembly/", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/pma/assembly/", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/pma/assembly/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/pma/assembly/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/pma/assembly/"],
                "moduleURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/index.html#page/pma/assembly/creo_parametric/aux_files/assemblydesign.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/index.html#page/pma/assembly/creo_parametric/aux_files/assemblydesign.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/index.html#page/pma/assembly/creo_parametric/aux_files/assemblydesign.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/index.html#page/pma/assembly/creo_parametric/aux_files/assemblydesign.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/index.html#page/pma/assembly/creo_parametric/aux_files/assemblydesign.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/index.html#page/pma/assembly/creo_parametric/aux_files/assemblydesign.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/index.html#page/pma/assembly/creo_parametric/aux_files/assemblydesign.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/index.html#page/pma/assembly/creo_parametric/aux_files/assemblydesign.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/index.html#page/pma/assembly/creo_parametric/aux_files/assemblydesign.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/index.html#page/pma/assembly/creo_parametric/aux_files/assemblydesign.html"],
                    "displayItem" : ["Assembly Design", "Baugruppenkonstruktion","Diseño de conjuntos","Conception d&apos;assemblages","Progettazione di assiemi","Конструкция сборки","アセンブリ設計","어셈블리 설계","装配设计","組件設計"],
            },
            "Advanced Framework Design": {
                "baseURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/pma/advanced_framework/", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/pma/advanced_framework/", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/pma/advanced_framework/", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/pma/advanced_framework/", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/pma/advanced_framework/", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/pma/advanced_framework/", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/pma/advanced_framework/", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/pma/advanced_framework/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/pma/advanced_framework/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/pma/advanced_framework/"],
                "moduleURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/index.html#page/pma/advanced_framework/creo_parametric/aux_files/advanced_framework_design.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/index.html#page/pma/advanced_framework/creo_parametric/aux_files/advanced_framework_design.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/index.html#page/pma/advanced_framework/creo_parametric/aux_files/advanced_framework_design.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/index.html#page/pma/advanced_framework/creo_parametric/aux_files/advanced_framework_design.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/index.html#page/pma/advanced_framework/creo_parametric/aux_files/advanced_framework_design.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/index.html#page/pma/advanced_framework/creo_parametric/aux_files/advanced_framework_design.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/index.html#page/pma/advanced_framework/creo_parametric/aux_files/advanced_framework_design.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/index.html#page/pma/advanced_framework/creo_parametric/aux_files/advanced_framework_design.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/index.html#page/pma/advanced_framework/creo_parametric/aux_files/advanced_framework_design.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/index.html#page/pma/advanced_framework/creo_parametric/aux_files/advanced_framework_design.html"],
                    "displayItem" : ["Advanced Framework Design", "Advanced Framework Design","Diseño avanzado de estructuras","Conception avancée de structures","Progettazione in Creo Advanced Framework","Advanced Framework Design","アドバンスフレーム設計","고급 구조물 설계","高级框架设计","進階框架設計"],

            },
            "Welding Design": {
                "baseURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/pma/welding/", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/pma/welding/", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/pma/welding/", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/pma/welding/", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/pma/welding/", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/pma/welding/", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/pma/welding/", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/pma/welding/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/pma/welding/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/pma/welding/"],
                "moduleURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/index.html#page/pma/welding/creo_parametric/aux_files/welding.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/index.html#page/pma/welding/creo_parametric/aux_files/welding.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/index.html#page/pma/welding/creo_parametric/aux_files/welding.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/index.html#page/pma/welding/creo_parametric/aux_files/welding.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/index.html#page/pma/welding/creo_parametric/aux_files/welding.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/index.html#page/pma/welding/creo_parametric/aux_files/welding.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/index.html#page/pma/welding/creo_parametric/aux_files/welding.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/index.html#page/pma/welding/creo_parametric/aux_files/welding.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/index.html#page/pma/welding/creo_parametric/aux_files/welding.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/index.html#page/pma/welding/creo_parametric/aux_files/welding.html"],
                    "displayItem" : ["Welding Design", "Schweißkonstruktion","Diseño de soldaduras","Conception de soudures","Progettazione di saldature","Конструирование сварных швов","溶接設計","용접 설계","焊接设计","焊接設計"],

            },
            "Electrical Design": {
                "baseURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/pma/electrical_design/", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/pma/electrical_design/", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/pma/electrical_design/", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/pma/electrical_design/", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/pma/electrical_design/", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/pma/electrical_design/", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/pma/electrical_design/", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/pma/electrical_design/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/pma/electrical_design/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/pma/electrical_design/"],
                "moduleURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/index.html#page/pma/electrical_design/creo_parametric/aux_files/electricaldesign.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/index.html#page/pma/electrical_design/creo_parametric/aux_files/electricaldesign.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/index.html#page/pma/electrical_design/creo_parametric/aux_files/electricaldesign.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/index.html#page/pma/electrical_design/creo_parametric/aux_files/electricaldesign.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/index.html#page/pma/electrical_design/creo_parametric/aux_files/electricaldesign.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/index.html#page/pma/electrical_design/creo_parametric/aux_files/electricaldesign.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/index.html#page/pma/electrical_design/creo_parametric/aux_files/electricaldesign.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/index.html#page/pma/electrical_design/creo_parametric/aux_files/electricaldesign.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/index.html#page/pma/electrical_design/creo_parametric/aux_files/electricaldesign.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/index.html#page/pma/electrical_design/creo_parametric/aux_files/electricaldesign.html"],
                    "displayItem" : ["Electrical Design", "Elektro-Design","Diseños eléctricos","Conception électrique","Progettazione elettrica","Конструирование электрики","電気設計","전기 설계","电气设计","電力設計"],

            },
            "Piping": {
                "baseURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/pma/piping/", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/pma/piping/", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/pma/piping/", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/pma/piping/", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/pma/piping/", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/pma/piping/", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/pma/piping/", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/pma/piping/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/pma/piping/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/pma/piping/"],
                "moduleURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/index.html#page/pma/piping/creo_parametric/aux_files/piping.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/index.html#page/pma/piping/creo_parametric/aux_files/piping.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/index.html#page/pma/piping/creo_parametric/aux_files/piping.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/index.html#page/pma/piping/creo_parametric/aux_files/piping.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/index.html#page/pma/piping/creo_parametric/aux_files/piping.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/index.html#page/pma/piping/creo_parametric/aux_files/piping.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/index.html#page/pma/piping/creo_parametric/aux_files/piping.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/index.html#page/pma/piping/creo_parametric/aux_files/piping.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/index.html#page/pma/piping/creo_parametric/aux_files/piping.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/index.html#page/pma/piping/creo_parametric/aux_files/piping.html"],
                    "displayItem" : ["Piping", "Rohrverlegung","Tubería","Tuyauterie","Tubazione","Трубопроводы","パイピング","파이핑","管道","管路"],

            },
            "Manufacturing": {
                "baseURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/pma/manufacturing/", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/pma/manufacturing/", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/pma/manufacturing/", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/pma/manufacturing/", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/pma/manufacturing/", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/pma/manufacturing/", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/pma/manufacturing/", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/pma/manufacturing/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/pma/manufacturing/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/pma/manufacturing/"],
                "moduleURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/index.html#page/pma/manufacturing/creo_parametric/aux_files/manufacturing.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/index.html#page/pma/manufacturing/creo_parametric/aux_files/manufacturing.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/index.html#page/pma/manufacturing/creo_parametric/aux_files/manufacturing.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/index.html#page/pma/manufacturing/creo_parametric/aux_files/manufacturing.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/index.html#page/pma/manufacturing/creo_parametric/aux_files/manufacturing.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/index.html#page/pma/manufacturing/creo_parametric/aux_files/manufacturing.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/index.html#page/pma/manufacturing/creo_parametric/aux_files/manufacturing.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/index.html#page/pma/manufacturing/creo_parametric/aux_files/manufacturing.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/index.html#page/pma/manufacturing/creo_parametric/aux_files/manufacturing.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/index.html#page/pma/manufacturing/creo_parametric/aux_files/manufacturing.html"],
                    "displayItem" : ["Manufacturing", "Fertigung","Mecanizado","Fabrication","Fabbricazione","Производство","製造","제조","制造","製造"],

            },
            "Mold Design and Casting": {
                "baseURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/pma/mold_and_casting/", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/pma/mold_and_casting/", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/pma/mold_and_casting/", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/pma/mold_and_casting/", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/pma/mold_and_casting/", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/pma/mold_and_casting/", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/pma/mold_and_casting/", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/pma/mold_and_casting/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/pma/mold_and_casting/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/pma/mold_and_casting/"],
                "moduleURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/index.html#page/pma/mold_and_casting/creo_parametric/aux_files/molddesignandcasting.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/index.html#page/pma/mold_and_casting/creo_parametric/aux_files/molddesignandcasting.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/index.html#page/pma/mold_and_casting/creo_parametric/aux_files/molddesignandcasting.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/index.html#page/pma/mold_and_casting/creo_parametric/aux_files/molddesignandcasting.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/index.html#page/pma/mold_and_casting/creo_parametric/aux_files/molddesignandcasting.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/index.html#page/pma/mold_and_casting/creo_parametric/aux_files/molddesignandcasting.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/index.html#page/pma/mold_and_casting/creo_parametric/aux_files/molddesignandcasting.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/index.html#page/pma/mold_and_casting/creo_parametric/aux_files/molddesignandcasting.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/index.html#page/pma/mold_and_casting/creo_parametric/aux_files/molddesignandcasting.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/index.html#page/pma/mold_and_casting/creo_parametric/aux_files/molddesignandcasting.html"],
                    "displayItem" : ["Mold Design and Casting", "Spritzguss und Guss","Diseño de moldes y fundición","Conception de moules et fonderie","Progettazione di stampi e colata","Конструирование пресс-форм и литье","金型設計と鋳造","몰드 설계 및 캐스팅","模具设计与铸造","模具設計及鑄造"],

            },
            "Sheetmetal": {
                "baseURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/pma/sheetmetal/", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/pma/sheetmetal/", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/pma/sheetmetal/", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/pma/sheetmetal/", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/pma/sheetmetal/", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/pma/sheetmetal/", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/pma/sheetmetal/", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/pma/sheetmetal/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/pma/sheetmetal/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/pma/sheetmetal/"],
                "moduleURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/index.html#page/pma/sheetmetal/creo_parametric/aux_files/sheetmetal.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/index.html#page/pma/sheetmetal/creo_parametric/aux_files/sheetmetal.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/index.html#page/pma/sheetmetal/creo_parametric/aux_files/sheetmetal.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/index.html#page/pma/sheetmetal/creo_parametric/aux_files/sheetmetal.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/index.html#page/pma/sheetmetal/creo_parametric/aux_files/sheetmetal.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/index.html#page/pma/sheetmetal/creo_parametric/aux_files/sheetmetal.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/index.html#page/pma/sheetmetal/creo_parametric/aux_files/sheetmetal.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/index.html#page/pma/sheetmetal/creo_parametric/aux_files/sheetmetal.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/index.html#page/pma/sheetmetal/creo_parametric/aux_files/sheetmetal.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/index.html#page/pma/sheetmetal/creo_parametric/aux_files/sheetmetal.html"],
                    "displayItem" : ["Sheetmetal", "Blech","Chapa","Tôlerie","Lamiera","Листовые изделия","シートメタル","판금","钣金件","鈑金"],

            },
            "Model Analysis": {
                "baseURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/pma/model_analysis/", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/pma/model_analysis/", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/pma/model_analysis/", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/pma/model_analysis/", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/pma/model_analysis/", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/pma/model_analysis/", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/pma/model_analysis/", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/pma/model_analysis/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/pma/model_analysis/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/pma/model_analysis/"],
                "moduleURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/index.html#page/pma/model_analysis/creo_parametric/aux_files/modelanalysis.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/index.html#page/pma/model_analysis/creo_parametric/aux_files/modelanalysis.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/index.html#page/pma/model_analysis/creo_parametric/aux_files/modelanalysis.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/index.html#page/pma/model_analysis/creo_parametric/aux_files/modelanalysis.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/index.html#page/pma/model_analysis/creo_parametric/aux_files/modelanalysis.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/index.html#page/pma/model_analysis/creo_parametric/aux_files/modelanalysis.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/index.html#page/pma/model_analysis/creo_parametric/aux_files/modelanalysis.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/index.html#page/pma/model_analysis/creo_parametric/aux_files/modelanalysis.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/index.html#page/pma/model_analysis/creo_parametric/aux_files/modelanalysis.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/index.html#page/pma/model_analysis/creo_parametric/aux_files/modelanalysis.html"],
                    "displayItem" : ["Model Analysis", "Modellanalyse","Análisis de modelos","Analyse de modèles","Analisi dei modelli","Анализ модели","モデル解析","모델 분석","模型分析","模型分析"],

            },
            "Simulation": {
                "baseURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/pma/simulate/", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/pma/simulate/", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/pma/simulate/", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/pma/simulate/", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/pma/simulate/", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/pma/simulate/", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/pma/simulate/", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/pma/simulate/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/pma/simulate/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/pma/simulate/"],
                "moduleURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/index.html#page/pma/simulate/creo_parametric/aux_files/simulation.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/index.html#page/pma/simulate/creo_parametric/aux_files/simulation.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/index.html#page/pma/simulate/creo_parametric/aux_files/simulation.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/index.html#page/pma/simulate/creo_parametric/aux_files/simulation.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/index.html#page/pma/simulate/creo_parametric/aux_files/simulation.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/index.html#page/pma/simulate/creo_parametric/aux_files/simulation.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/index.html#page/pma/simulate/creo_parametric/aux_files/simulation.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/index.html#page/pma/simulate/creo_parametric/aux_files/simulation.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/index.html#page/pma/simulate/creo_parametric/aux_files/simulation.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/index.html#page/pma/simulate/creo_parametric/aux_files/simulation.html"],
                    "displayItem" : ["Simulation", "Simulation","Simulación","Simulation","Simulazione","Расчет","シミュレーション","시뮬레이션","模拟","模擬"],

            },
            "Language Support": {
                "baseURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/pma/langsupport/", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/pma/langsupport/", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/pma/langsupport/", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/pma/langsupport/", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/pma/langsupport/", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/pma/langsupport/", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/pma/langsupport/", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/pma/langsupport/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/pma/langsupport/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/pma/langsupport/"],
                "moduleURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/index.html#page/pma/langsupport/creo_parametric/aux_files/languages.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/index.html#page/pma/langsupport/creo_parametric/aux_files/languages.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/index.html#page/pma/langsupport/creo_parametric/aux_files/languages.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/index.html#page/pma/langsupport/creo_parametric/aux_files/languages.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/index.html#page/pma/langsupport/creo_parametric/aux_files/languages.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/index.html#page/pma/langsupport/creo_parametric/aux_files/languages.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/index.html#page/pma/langsupport/creo_parametric/aux_files/languages.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/index.html#page/pma/langsupport/creo_parametric/aux_files/languages.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/index.html#page/pma/langsupport/creo_parametric/aux_files/languages.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/index.html#page/pma/langsupport/creo_parametric/aux_files/languages.html"],
                    "displayItem" : ["Language Support", "Sprachunterstützung","Compatibilidad de idiomas","Prise en charge des langues","Supporto delle lingue","Поддержка языков","言語サポート","언어 지원","语言支持","語言支援"],

            },
            "Other Modules": {
                "baseURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/pma/other_modules/", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/pma/other_modules/", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/pma/other_modules/", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/pma/other_modules/", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/pma/other_modules/", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/pma/other_modules/", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/pma/other_modules/", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/pma/other_modules/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/pma/other_modules/", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/pma/other_modules/"],
                "moduleURL": ["http://help.ptc.com/creo_hc/creo30_pma_hc/usascii/index.html#page/pma/other_modules/creo_parametric/aux_files/othermodules.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/german/index.html#page/pma/other_modules/creo_parametric/aux_files/othermodules.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/spanish/index.html#page/pma/other_modules/creo_parametric/aux_files/othermodules.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/french/index.html#page/pma/other_modules/creo_parametric/aux_files/othermodules.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/italian/index.html#page/pma/other_modules/creo_parametric/aux_files/othermodules.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/russian/index.html#page/pma/other_modules/creo_parametric/aux_files/othermodules.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/japanese/index.html#page/pma/other_modules/creo_parametric/aux_files/othermodules.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/korean/index.html#page/pma/other_modules/creo_parametric/aux_files/othermodules.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_cn/index.html#page/pma/other_modules/creo_parametric/aux_files/othermodules.html", "http://help.ptc.com/creo_hc/creo30_pma_hc/chinese_tw/index.html#page/pma/other_modules/creo_parametric/aux_files/othermodules.html"],
                    "displayItem" : ["Other Modules", "Sonstige Module","Otros módulos","Autres modules","Altri moduli","Другие модули","その他のモジュール","기타 모듈","其它模块","其餘模組"],

            }
        },

        homeSiteHelpResources : {
        divClassID: "helpResourcesContainer",
        headerClassID: "helpResourcesHeaderID",
        // headerDisplayItem : Translate the text between square brackets in this order ["en", "de", "es", "fr", "it", "ru", "ja", "ko", "zh_CN", "zh_TW"]
        headerDisplayItem: ["Help Resources", "Hilfe-Ressourcen", "Recursos de la ayuda", "Ressources d'aide", "Risorse della Guida", "Ресурсы справки", "ヘルプリソース", "도움말 리소스", "帮助资源", "說明資源"],
        itemsClassID: "helpResourcesListItem",
        targetID: "_self",
        helpResources: {

            // displayItem :  Translate the text between square brackets in this order ["en", "de", "es", "fr", "it", "ru", "ja", "ko", "zh_CN", "zh_TW"]

            "PTC University Learning Exchange": {
                "resourceURL" : ["http://learningexchange.ptc.com/tutorials/by_product/ptc-creo/product_id:1","http://learningexchange.ptc.com/tutorials/by_product/ptc-creo/product_id:1", "http://learningexchange.ptc.com/tutorials/by_product/ptc-creo/product_id:1","http://learningexchange.ptc.com/tutorials/by_product/ptc-creo/product_id:1", "http://learningexchange.ptc.com/tutorials/by_product/ptc-creo/product_id:1","http://learningexchange.ptc.com/tutorials/by_product/ptc-creo/product_id:1", "http://learningexchange.ptc.com/tutorials/by_product/ptc-creo/product_id:1","http://learningexchange.ptc.com/tutorials/by_product/ptc-creo/product_id:1", "http://learningexchange.ptc.com/tutorials/by_product/ptc-creo/product_id:1","http://learningexchange.ptc.com/tutorials/by_product/ptc-creo/product_id:1"],
                    "displayItem" : ["PTC University Learning Exchange", "PTC University Learning Exchange","PTC University Learning Exchange","PTC University Learning Exchange","PTC University Learning Exchange","PTC University Learning Exchange","PTC University Learning Exchange","PTC University Learning Exchange","PTC University Learning Exchange","PTC University Learning Exchange"],
            },
            "PTC Creo Community" : {
                "resourceURL" : ["http://communities.ptc.com/community/creo", "http://communities.ptc.com/community/creo", "http://communities.ptc.com/community/creo", "http://communities.ptc.com/community/creo", "http://communities.ptc.com/community/creo", "http://communities.ptc.com/community/creo", "http://communities.ptc.com/community/creo", "http://communities.ptc.com/community/creo", "http://communities.ptc.com/community/creo", "http://communities.ptc.com/community/creo"],
                    "displayItem" : ["PTC Creo Community", "PTC Creo Community","Comunidad de PTC","Communauté PTC Creo","PTC Creo Community","Сообщество PTC Creo","PTC Creo コミュニティ","PTC Creo 커뮤니티","PTC Creo 社区","PTC Creo 社群"],
            },
            "eSupport" : {
                "resourceURL": ["https://www.ptc.com/appserver/cs/portal/", "https://www.ptc.com/appserver/cs/portal/", "https://www.ptc.com/appserver/cs/portal/", "https://www.ptc.com/appserver/cs/portal/", "https://www.ptc.com/appserver/cs/portal/", "https://www.ptc.com/appserver/cs/portal/", "https://www.ptc.com/appserver/cs/portal/", "https://www.ptc.com/appserver/cs/portal/", "https://www.ptc.com/appserver/cs/portal/", "https://www.ptc.com/appserver/cs/portal/"],
                    "displayItem" : ["eSupport", "eSupport","eSupport","eSupport","eSupport","eSupport","eSupport","eSupport","eSupport","eSupport"],
            },
            "Contact PTC": {
                "resourceURL": ["http://www.ptc.com/company/contacts/index.htm", "http://de.ptc.com/about/contact-us", "http://es.ptc.com/about/contact-us", "http://fr.ptc.com/about/contact-us", "http://it.ptc.com/about/contact-us", "http://www.ptc.com/company/contacts/index.htm", "http://ja.ptc.com/about/contact-us", "http://ko.ptc.com/about/contact-us", "http://zh-cn.ptc.com/about/contact-us", "http://zh-tw.ptc.com/about/contact-us"],
                    "displayItem" : ["Contact Support", "Support kontaktieren","Contacto con el soporte técnico","Contacter le Support","Contatta il supporto","Обратиться в группу поддержки","サポートへのお問い合わせ","지원 문의","联系技术支持","聯絡支援人員"],
            }
        }
        }
    };

var homeSitePopularSearches = 
    {
        classID : "popSearch",
        onclickEvent : "popSearchF",
        hrefCall : "javascript:void(0);",
        popSearches : ["round", "skeleton", "revolve","contstraint","BOM","mechanism","assembly","curve","part","UDFs","draw","simplified","render"],
        popSearchesPercentage : [100, 200, 100, 120, 150, 90, 100, 100, 60, 100, 100, 150, 120]
    };

var homeSiteFooterLinks = 
    {
        divClassID: "footerLinksContainer",
        headerClass: "footerLinksHeader",
        itemsClassID: "footerLinksAnchorItem",
        targetID: "_self",
        footerLinks: {

            // displayItem :  Translate the text between square brackets in this order ["en", "de", "es", "fr", "it", "ru", "ja", "ko", "zh_CN", "zh_TW"]

            "Site Map": {
                "resourceURL": ["http://www.ptc.com/common/sitemap/index.htm", "http://de.ptc.com/common/sitemap/index.htm", "http://es.ptc.com/common/sitemap/index.htm", "http://fr.ptc.com/common/sitemap/index.htm", "http://it.ptc.com/common/sitemap/index.htm", "http://ptc.com/common/sitemap/index.htm", "http://ja.ptc.com/common/sitemap/index.htm", "http://ko.ptc.com/common/sitemap/index.htm", "http://zh-cn.ptc.com/common/sitemap/index.htm", "http://zh-tw.ptc.com/common/sitemap/index.htm"],
                    "displayItem" : ["Site Map", "Siteübersicht","Mapa del sitio","Plan du site","Mappa del sito","Карта сайта","サイト マップ","사이트 맵","站点地图","網站地圖"],
            },
            "Softwar Privacy": {
                "resourceURL": ["http://www.ptc.com/company/piracy/index.htm", "http://de.ptc.com/company/piracy/index.htm", "http://es.ptc.com/company/piracy/index.htm", "http://fr.ptc.com/company/piracy/index.htm", "http://it.ptc.com/company/piracy/index.htm", "http://ptc.com/company/piracy/index.htm", "http://ja.ptc.com/company/piracy/index.htm", "http://ko.ptc.com/company/piracy/index.htm", "http://zh-cn.ptc.com/company/piracy/index.htm", "http://zh-tw.ptc.com/company/piracy/index.htm"],
                    "displayItem" : ["Software Piracy", "Softwarepiraterie","Piratería de software","Piratage de logiciels","Pirateria software","Нелегальное использование ПО","ソフトウェアの著作権侵害","소프트웨어 불법복제","软件盗版","軟體盜版"],
            },
            "Legal Policies, Agreements Disclaimers": {
                "resourceURL": ["http://www.ptc.com/company/policies/index.htm", "http://de.ptc.com/company/policies/index.htm", "http://es.ptc.com/company/policies/index.htm", "http://fr.ptc.com/company/policies/index.htm", "http://it.ptc.com/company/policies/index.htm", "http://ptc.com/company/policies/index.htm", "http://ja.ptc.com/company/policies/index.htm", "http://ko.ptc.com/company/policies/index.htm", "http://zh-cn.ptc.com/company/policies/index.htm", "http://zh-tw.ptc.com/company/policies/index.htm"],
                    "displayItem" : ["Legal Policies Agreements and Disclaimers", "Rechtliche Richtlinien, Vereinbarungen und Ausschlüsse","Avisos legales, convenios y exenciones de responsabilidad","Dispositions légales, accords et décharges de responsabilité","Note legali, contratti e dichiarazioni di non responsabilità","Положения и условия, соглашения и заявления об отказе от ответственности","法律上の方針、合意事項、免責事項","법률 정책, 계약 및 고지 사항","法律政策、协议和免责声明","法律政策、合約與免責聲明"],
            },
            "WorldWide Sites": {
                "resourceURL": ["http://www.ptc.com/appserver/common/locale/options.jsp", "http://de.ptc.com/appserver/common/locale/options.jsp", "http://es.ptc.com/appserver/common/locale/options.jsp", "http://fr.ptc.com/appserver/common/locale/options.jsp", "http://it.ptc.com/appserver/common/locale/options.jsp", "http://ptc.com/appserver/common/locale/options.jsp", "http://ja.ptc.com/appserver/common/locale/options.jsp", "http://ko.ptc.com/appserver/common/locale/options.jsp", "http://zh-cn.ptc.com/appserver/common/locale/options.jsp", "http://zh-tw.ptc.com/appserver/common/locale/options.jsp"],
                    "displayItem" : ["WorldWide Sites", "Internationale Sites","Sitios de otros países","Sites dans le monde","Siti internazionali","Международные сайты","世界各国のサイト","전 세계 사이트","全球站点","全球網站"],
            },
            "Find a reseller": {
                "resourceURL": ["http://www.ptc.com/appserver/wcms/partners/resellers/search.jsp", "http://de.ptc.com/appserver/wcms/partners/resellers/search.jsp", "http://es.ptc.com/appserver/wcms/partners/resellers/search.jsp", "http://fr.ptc.com/appserver/wcms/partners/resellers/search.jsp", "http://it.ptc.com/appserver/wcms/partners/resellers/search.jsp", "http://ptc.com/appserver/wcms/partners/resellers/search.jsp", "http://ja.ptc.com/appserver/wcms/partners/resellers/search.jsp", "http://ko.ptc.com/appserver/wcms/partners/resellers/search.jsp", "http://zh-cn.ptc.com/appserver/wcms/partners/resellers/search.jsp", "http://zh-tw.ptc.com/appserver/wcms/partners/resellers/search.jsp"],
                    "displayItem" : ["Find a reseller", "Vertriebspartner suchen","Buscar un distribuidor","Rechercher un revendeur","Ricerca di un rivenditore","Поиск реселлера","販売代理店の検索","리셀러 찾기","查找代理商","尋找經銷商"],
            },
            "Contact": {
                "resourceURL": ["http://www.ptc.com/company/contacts/index.htm", "http://de.ptc.com/about/contact-us", "http://es.ptc.com/about/contact-us", "http://fr.ptc.com/about/contact-us", "http://it.ptc.com/about/contact-us", "http://ptc.com/company/contacts/index.htm", "http://ja.ptc.com/about/contact-us", "http://ko.ptc.com/about/contact-us", "http://zh-cn.ptc.com/about/contact-us", "http://zh-tw.ptc.com/about/contact-us"],
                    "displayItem" : ["Contact PTC", "Kontakt zu PTC","Contacto con PTC","Contacter PTC","Contatta PTC","Обратиться в PTC","PTC へのお問い合わせ","PTC 문의","联系 PTC","聯絡 PTC"],
            },
            "Copyright": {
                "resourceURL": ["http://www.ptc.com/common/ptccopy.htm", "http://de.ptc.com/common/ptccopy.htm", "http://es.ptc.com/common/ptccopy.htm", "http://fr.ptc.com/common/ptccopy.htm", "http://it.ptc.com/common/ptccopy.htm", "http://ptc.com/common/ptccopy.htm", "http://ja.ptc.com/common/ptccopy.htm", "http://ko.ptc.com/common/ptccopy.htm", "http://zh-cn.ptc.com/common/ptccopy.htm", "http://zh-tw.ptc.com/common/ptccopy.htm"],
                    "displayItem" : ["PTC Copyright 2014, PTC Inc.", "PTC Copyright 2014, PTC Inc.","PTC Copyright 2014, PTC Inc. ","PTC Copyright 2014, PTC Inc.","PTC Copyright 2014, PTC Inc.","PTC (С) 2014, PTC Inc. ","PTC Copyright 2014, PTC Inc.","PTC Copyright 2014, PTC Inc. ","PTC 版权所有 2014, PTC Inc. ","© 2014 PTC Inc. 著作權所有"],
            }
        }
    };
